name: sv
channels:
  - oggm
  - conda-forge
  # - defaults
dependencies:
  - dask #=2.3.0=py_0
  - geopandas #=0.5.1=py_0
  - ipyleaflet #=0.11.1=py37_1
  - ipywidgets #=7.5.1=py_0
  - jupyter #=1.0.0=py_2
  - jupyterlab #=1.1.1=py_0
  - matplotlib #=3.1.1=py37_1
  - netcdf4 #=1.5.1.2=py37h73a1b54_1
  - pytest #=5.1.2=py37_0
  - rasterio #=1.0.26=py37hdff7cfa_1
  - requests #=2.22.0=py37_1
  - salem #=0.2.4.201906261358=py_0
  - seaborn #=0.9.0=py_1
  - siphon #=0.8.0=py37_1001
  - tqdm #=4.35.0=py_0
  - xarray #=0.12.3=py_0
  - coverage
  # Below is needed for another package serving API endpoints over HTTP.
  - flask
  - flask-cors
  - intake
  - regionmask
  - birdy
  - marshmallow 
  - apispec
 - pip:
    - sat-search==0.2.0
    - jupyter-server-proxy
    - apispec-webframeworks
    - dask-labextension==0.3.1
    - git+https://github.com/NCAR/intake-thredds
